Create a new endpoint /API/UploadWordLinkRecording.php
techteam25/ROCC pull request #6
Opened 2024-02-09 14:16 UTC by spcheema

### Summary of changes

- Add a new endpoint for uploading word link recording
   -  endpoint path is `/API/UploadWordLinkRecording.php`
-  Refactor common test code to the abstract class
- Add e2e test for `UploadWordLinkRecording.php ` endpoint

Link to endpoint discussion:

https://docs.google.com/document/d/1Wr5W2BDVl17DCicBFGvkG4darD51CZaWZ75GPhX2ols/edit

2024-02-11 15:34 UTC, johntseng requested changes

2024-02-11 15:34 UTC, johntseng commented on API/UploadWordLinkRecording.php
> +    RespondWithError(400, "Project must be registered before audio can be uploaded");
Please update error message to "Please /API/RegisterPhone.php before /API/UploadWordLinkRecording.php".

2024-02-11 15:34 UTC, johntseng commented on tests/integration/UploadWordLinkRecordingIntegrationTest.php
> +            'RecordingId' => $recordingId
The update request should not require a recording id. The API should upsert based on phoneId, term.

2024-02-11 15:34 UTC, johntseng commented on API/utils/Model.php
> +            # save recording file content
Please save recording before commit. In case of error, orphaned files are preferable to missing files.

2024-02-11 15:34 UTC, johntseng commented on API/utils/Model.php
> +            RespondWithError(500, $e->getMessage());
Please do not leak the error message. Instead, return a generic error like "There was an exception creating the world link recording."

2024-02-11 15:34 UTC, johntseng commented on API/utils/Model.php
> +            # save recording file content
During update, let's do 1. save new file, 2. commit, 3. delete old file, so that we minimize the chance of missing files.

2024-02-11 15:34 UTC, johntseng commented on API/utils/Model.php
> +                 throw new \Exception("Failed to deleted existing recording file: $existingRecodingFilepath");
Let's log the error but don't throw. It's undesirable to not delete the file, but it's acceptable to have orphaned files.

2024-02-11 15:34 UTC, johntseng commented on API/utils/Model.php
> +        return  sprintf("%s.%s", bin2hex(random_bytes(20)), $recordingFileExtension);
Please remove extra space between "return" and "sprintf"

2024-02-11 15:34 UTC, johntseng commented on API/utils/Model.php
> +        $recordingFileExtension = pathinfo($audioRecordingFilename, PATHINFO_EXTENSION);
Can you validate that extension is ascii alphanumeric only? e.g. regex `[A-Za-z0-9]`. Doesn't seem like pathinfo already does that.

2024-02-11 15:34 UTC, johntseng commented on docs/new-schema.sql
> +--   androidId CHAR(16) NOT NULL,
What is androidId for?

2024-02-11 15:34 UTC, johntseng commented on tests/integration/UploadWordLinkRecordingIntegrationTest.php
> +        // verify auto recording is uploaded successfully
auto recording? Do you mean audio?

2024-02-11 15:34 UTC, johntseng commented on tests/integration/UploadWordLinkRecordingIntegrationTest.php
> +    public function testShouldNotUpdateGivenRecordingIfTermIsChanged() {
Since recordingId will not be provided in the update operation, this test should create a new recording.

2024-02-11 22:49 UTC, spcheema commented on API/UploadWordLinkRecording.php
> +    RespondWithError(400, "Project must be registered before audio can be uploaded");
`Please /API/RegisterPhone.php before /API/UploadWordLinkRecording.php` It's not clear much I 'd suggest something like `Please register a project using /API/RegisterPhone.php before /API/UploadWordLinkRecording.php`

2024-02-11 22:51 UTC, spcheema commented on tests/integration/UploadWordLinkRecordingIntegrationTest.php
> +            'RecordingId' => $recordingId
I thought it'll be consistent with `UploadSlideBacktranslation.php` I'll remove it.

2024-02-11 22:54 UTC, spcheema commented on API/utils/Model.php
> +                 throw new \Exception("Failed to deleted existing recording file: $existingRecodingFilepath");
Done.

2024-02-11 22:56 UTC, spcheema commented on docs/new-schema.sql
> +--   androidId CHAR(16) NOT NULL,
That's clean up I forgot. I used project id to resolve `androidId` in the payload.

2024-02-11 22:56 UTC, spcheema commented on tests/integration/UploadWordLinkRecordingIntegrationTest.php
> +        // verify auto recording is uploaded successfully
Typo.. pls ingnore.. fixed.

2024-02-11 23:03 UTC, spcheema commented on API/utils/Model.php
> +        $recordingFileExtension = pathinfo($audioRecordingFilename, PATHINFO_EXTENSION);
How about the length of the extension? Validation is performed here.

https://github.com/techteam25/ROCC/blob/fa5051163066034c4e4a3454547eda43a3600a06/API/UploadWordLinkRecording.php#L28-L31


Should we update the error message generic like `File extension is not valid in the audioRecordingFilename`?

2024-02-11 23:04 UTC, spcheema commented on API/utils/Model.php
> +        $recordingFileExtension = pathinfo($audioRecordingFilename, PATHINFO_EXTENSION);
`GenerateRecordingFileName` func will remain as-is just to extract the file extension.

2024-02-11 23:06 UTC, spcheema commented on API/utils/Model.php
> +            RespondWithError(500, $e->getMessage());
My bad.. I left is for testing purposes. Remove from response.

2024-02-11 23:07 UTC, spcheema commented on API/utils/Model.php
> +            # save recording file content
If orphaned files are preferable then I'll update the order.

2024-02-11 23:13 UTC, spcheema commented on API/utils/Model.php
> +            # save recording file content
Since we are going to keep orphaned files, I have increased the random filename length to 30 just to make chance of duplication are far away from minimal

2024-02-12 00:20 UTC, spcheema commented on tests/integration/UploadWordLinkRecordingIntegrationTest.php
> +    public function testShouldNotUpdateGivenRecordingIfTermIsChanged() {
Yes both of them `testShouldNotUpdateGivenRecordingIfTermIsChanged ` & `testShouldNotUpdateGivenRecordingIfPhoneIdIsChanged`

2024-02-12 02:44 UTC, johntseng commented on API/UploadWordLinkRecording.php
> +    RespondWithError(400, "Project must be registered before audio can be uploaded");
Looks great. Thanks.

2024-02-12 02:46 UTC, johntseng commented on API/utils/Model.php
> +        $recordingFileExtension = pathinfo($audioRecordingFilename, PATHINFO_EXTENSION);
Let's do length of 1 to 100. I don't think any reasonable extension is longer than 100.

2024-02-12 04:43 UTC, spcheema commented on API/utils/Model.php
> +        $recordingFileExtension = pathinfo($audioRecordingFilename, PATHINFO_EXTENSION);
It's implemented now. thanks for confirming.

2024-02-12 07:07 UTC, spcheema commented
@johntseng  All comments are addressed. Thanks for reviewing the PR.

2024-02-12 07:09 UTC, spcheema commented
`AddFileToStorage` method doesn't exist in the `Model.php` but it's used in many places.

https://github.com/techteam25/ROCC/blob/5eea8b166ecde6305e74a43bbc6384b5e3885064/API/utils/Model.php#L279

2024-02-13 03:21 UTC, johntseng requested changes

2024-02-13 03:21 UTC, johntseng commented on API/UploadWordLinkRecording.php
> +    RespondWithError(400, "File extension is not valid in the audioRecordingFilename");
Please be more specific: File extension should match /^[A-Za-z0-9]{1,100}$/

2024-02-13 03:21 UTC, johntseng commented on API/utils/Model.php
> +    public function IsRecordingExists($projectId, $term)
Is this method no longer used? Please remove.

2024-02-13 03:21 UTC, johntseng commented on tests/integration/UploadWordLinkRecordingIntegrationTest.php
> +    const RECORDING_FILE_NAME_2 = "WordLinks 2.." . self::RECORDING_FILE_EXTENSION;
Typo: "WordLinks 2." with just one period.

2024-02-13 03:21 UTC, johntseng commented on tests/integration/UploadWordLinkRecordingIntegrationTest.php
> +        # verify exiting recording data isn't changed
Here, you're verifying the $createdRecording that was loaded before sending $updateRecordingPayload, so nothing would change. You can remove this section. 

Instead, please verify the WordlinkRecordings has been updated successfully.

2024-02-13 03:21 UTC, johntseng commented on tests/integration/UploadWordLinkRecordingIntegrationTest.php
> +        # verify exiting recording data isn't changed
Before verifying that the data isn't changed, please reload the data from the database again.

2024-02-13 03:21 UTC, johntseng commented on tests/integration/UploadWordLinkRecordingIntegrationTest.php
> +        // verify audio recording is uploaded successfully
Please also assert `this->getRecording($updatedRecordingId)`.

2024-02-13 03:21 UTC, johntseng commented on tests/integration/BaseIntegrationTest.php
> +        $q = self::$db->prepare('SELECT id FROM Projects where androidId = ?');
Can you use GetProjectId from Model?

2024-02-13 03:53 UTC, spcheema commented on tests/integration/BaseIntegrationTest.php
> +        $q = self::$db->prepare('SELECT id FROM Projects where androidId = ?');
Yeah we can do that actually.

2024-02-13 04:12 UTC, spcheema commented on tests/integration/UploadWordLinkRecordingIntegrationTest.php
> +        // verify audio recording is uploaded successfully
Sorry, I didn't get the point of why we need to assert it again. Since creating a recording is already asserted we do need to again here again. I even removed the following lines `// verify audio recording is uploaded successfully` after which we redundant.

2024-02-13 04:13 UTC, spcheema commented on tests/integration/UploadWordLinkRecordingIntegrationTest.php
> +        # verify exiting recording data isn't changed
Yeah good idea.. reloaded from DB after the update reqeust

2024-02-13 04:18 UTC, johntseng commented on tests/integration/UploadWordLinkRecordingIntegrationTest.php
> +        // verify audio recording is uploaded successfully
The above block asserts for $recordingId. Please assert for $updatedRecordingId.

2024-02-13 05:13 UTC, spcheema commented on API/UploadWordLinkRecording.php
> +    RespondWithError(400, "File extension is not valid in the audioRecordingFilename");
Done

2024-02-13 05:13 UTC, spcheema commented on API/utils/Model.php
> +    public function IsRecordingExists($projectId, $term)
Removed, thanks for pointing out.

2024-02-13 05:20 UTC, spcheema commented on tests/integration/UploadWordLinkRecordingIntegrationTest.php
> +        # verify exiting recording data isn't changed
Both `testShouldNotUpdateGivenRecordingIfTermIsChanged` & `testShouldNotUpdateGivenRecordingIfPhoneIdIsChanged` are updated to load created recording data from the database after the update request.

`verify the WordlinkRecordings has been updated successfully.` is asserted in the previous test. No need to do it again over here.

2024-02-13 05:31 UTC, spcheema commented on tests/integration/UploadWordLinkRecordingIntegrationTest.php
> +        // verify audio recording is uploaded successfully
Is below understanding correct?

1. Create recording - `#1` is created.
2. Update recording with different `term` and/or `androidId` .
3. Assert to make sure a new recording is created i.e.  `#2` instead of updating `#1`
4. Assert that recording `#1` data is intact
5. Assert recording `#2` is data saved successfully.  

If my understanding is correct then `step 2` is just creating a new story so I don't think we need to assert it again. Since it's already asserted twice in pervious tests.


I am happy to do that but it's overkill. I don't find it much useful. Lemme know if you really want to do it.

2024-02-13 05:35 UTC, johntseng commented on tests/integration/UploadWordLinkRecordingIntegrationTest.php
> +        // verify audio recording is uploaded successfully
You're right.

2024-02-13 05:36 UTC, johntseng commented on tests/integration/UploadWordLinkRecordingIntegrationTest.php
> +        // verify auto recording is uploaded successfully
Please change comment to "verify audio recording isn't changed". Here and below.

2024-02-13 05:37 UTC, spcheema commented on tests/integration/UploadWordLinkRecordingIntegrationTest.php
> +        // verify auto recording is uploaded successfully
Already changed to ` verify created recording content is intact with update request`

2024-02-13 05:38 UTC, spcheema commented on tests/integration/UploadWordLinkRecordingIntegrationTest.php
> +        // verify auto recording is uploaded successfully
Or we can say `verify previously created recording content is intact with the update recording request`.

2024-02-16 16:56 UTC, merged